
package libraryserver;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LibraryServiceImpl", targetNamespace = "http://libraryserver/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibraryServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<libraryserver.Book>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookByAuthor", targetNamespace = "http://libraryserver/", className = "libraryserver.GetBookByAuthor")
    @ResponseWrapper(localName = "getBookByAuthorResponse", targetNamespace = "http://libraryserver/", className = "libraryserver.GetBookByAuthorResponse")
    @Action(input = "http://libraryserver/LibraryServiceImpl/getBookByAuthorRequest", output = "http://libraryserver/LibraryServiceImpl/getBookByAuthorResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://libraryserver/LibraryServiceImpl/getBookByAuthor/Fault/Exception")
    })
    public List<Book> getBookByAuthor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<libraryserver.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://libraryserver/", className = "libraryserver.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://libraryserver/", className = "libraryserver.GetAllBooksResponse")
    @Action(input = "http://libraryserver/LibraryServiceImpl/getAllBooksRequest", output = "http://libraryserver/LibraryServiceImpl/getAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param arg0
     * @return
     *     returns libraryserver.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findBookById", targetNamespace = "http://libraryserver/", className = "libraryserver.FindBookById")
    @ResponseWrapper(localName = "findBookByIdResponse", targetNamespace = "http://libraryserver/", className = "libraryserver.FindBookByIdResponse")
    @Action(input = "http://libraryserver/LibraryServiceImpl/findBookByIdRequest", output = "http://libraryserver/LibraryServiceImpl/findBookByIdResponse")
    public Book findBookById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewBook", targetNamespace = "http://libraryserver/", className = "libraryserver.AddNewBook")
    @ResponseWrapper(localName = "addNewBookResponse", targetNamespace = "http://libraryserver/", className = "libraryserver.AddNewBookResponse")
    @Action(input = "http://libraryserver/LibraryServiceImpl/addNewBookRequest", output = "http://libraryserver/LibraryServiceImpl/addNewBookResponse")
    public String addNewBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteBook", targetNamespace = "http://libraryserver/", className = "libraryserver.DeleteBook")
    @ResponseWrapper(localName = "deleteBookResponse", targetNamespace = "http://libraryserver/", className = "libraryserver.DeleteBookResponse")
    @Action(input = "http://libraryserver/LibraryServiceImpl/deleteBookRequest", output = "http://libraryserver/LibraryServiceImpl/deleteBookResponse")
    public void deleteBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateBook", targetNamespace = "http://libraryserver/", className = "libraryserver.UpdateBook")
    @ResponseWrapper(localName = "updateBookResponse", targetNamespace = "http://libraryserver/", className = "libraryserver.UpdateBookResponse")
    @Action(input = "http://libraryserver/LibraryServiceImpl/updateBookRequest", output = "http://libraryserver/LibraryServiceImpl/updateBookResponse")
    public String updateBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
